### ISSUE TITLE
Windows 10 Universal App Support

### ISSUE THREAD

**Issue by npag** [brandon-barker/PushBots.NET#1]
Is there any chanse this awesome library will be supported by Win10? Currently, NuGet will not let me add it to my project because it is not a Win8.1 Universal App Project.

**Comment by brandon-barker** [comment]
Thanks, I'll look into adding support for this in the next few days.

In the meantime you're welcome to submit a PR if you like ;)

**Comment by npag** [comment]
Thank you very much for having a look. I would submit a PR if I knew what to do to make it run on Windows10 Universal Platform. Unfortunately I am still very new to C# :/
