### ISSUE TITLE
Get All Devices is not working

### ISSUE THREAD

**Issue by kdudek89** [brandon-barker/PushBots.NET#4]
Hi,

Could you please fix GetAllDevices in the library ??

{"Message":"Cannot deserialize the current JSON object (e.g. {\"name\":\"value\"}) into type 'System.Collections.Generic.List`1[PushBots.NET.Models.Device]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.\r\nTo fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.\r\nPath 'code', line 1, position 8."}

**Comment by brandon-barker** [comment]
Hi,

As per issue #3, unfortunately this functionality has been deprecated from the PushBots API
